[build]
builder = "paketobuildpacks/builder:base"

[deploy]
startCommand = "cd backend && python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "cd backend && python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo '=== FINAL CHECK ==='",
    "which python || echo 'No python found'",
    "which python3 || echo 'No python3 found'",
    "ls -la /nix/store/ | grep python || echo 'No python in nix store'",
    "python -V || echo 'Python execution failed'",
    "cd backend"
]
