[build]
builder = "nixpacks"
providers = ["python"]

[deploy]
startCommand = "echo '[DEPLOY] Starting...' && which python3 && python3 -V && cd backend && python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT --log-level debug"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = [
    "python3",
    "python3Packages.pip",
    "python3Packages.uvicorn"
]

[phases.install]
cmds = [
    "echo '[INSTALL] Starting...'",
    "which python3",
    "python3 -V",
    "echo '[INSTALL] Installing pip'",
    "python3 -m pip install --upgrade pip",
    "echo '[INSTALL] Installing requirements'",
    "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo '[BUILD] Starting...'",
    "which python3",
    "python3 -V",
    "cd backend"
]