[build]
builder = "nixpacks"
providers = ["python"]

[deploy]
startCommand = "ls -la && echo 'Python location:' && which python3 || true && echo 'Python version:' && python3 -V || true && echo 'Starting server...' && cd backend && python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT --log-level debug"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = [
    "python3",
    "python3Packages.pip",
    "python3Packages.uvicorn"
]

[phases.install]
cmds = [
    "ls -la",
    "echo 'Python location:' && which python3 || true",
    "echo 'Python version:' && python3 -V || true",
    "echo 'Installing pip...'",
    "python3 -m pip install --upgrade pip || true",
    "echo 'Installing requirements...'",
    "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "ls -la",
    "echo 'Python location:' && which python3 || true",
    "echo 'Python version:' && python3 -V || true",
    "cd backend"
]