[build]
builder = "nixpacks"
providers = ["python"]

[deploy]
startCommand = "echo '[DEPLOY] Starting...' && echo '[DEPLOY] PATH=' && echo $PATH && echo '[DEPLOY] Python=' && which python3 && cd backend && python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = [
    "python3",
    "python3Packages.pip",
    "python3Packages.uvicorn"
]

[phases.install]
cmds = [
    "echo '[INSTALL] Starting...'",
    "echo '[INSTALL] PATH='",
    "echo $PATH",
    "echo '[INSTALL] Python='",
    "which python3",
    "echo '[INSTALL] Installing pip'",
    "python3 -m pip install --upgrade pip",
    "echo '[INSTALL] Installing requirements'",
    "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo '[BUILD] Starting...'",
    "echo '[BUILD] Python version='",
    "python3 -V",
    "cd backend"
]