[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python311"]
aptPkgs = ["python3-pip", "python3-dev", "build-essential"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip install -r backend/requirements.txt"] 