[build]
builder = "nixpacks"
providers = ["python"]

[deploy]
startCommand = "cd backend && python3.11 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.uvicorn",
    "gcc"
]

[phases.install]
cmds = [
    "python3.11 -m pip install --upgrade pip",
    "cd backend && python3.11 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd backend"]