[build]
builder = "nixpacks"
providers = ["python"]

[deploy]
startCommand = "cd backend && python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = [
    "python3",
    "python3Packages.pip",
    "python3Packages.uvicorn"
]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd backend"]