[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo '=== FINAL CHECK ===' ",
    "find / -name python3 2>/dev/null || echo 'No python3 found'",
    "ls -la /nix/var/nix/profiles/default/bin/ || echo 'No nix profile bin'",
    "/nix/var/nix/profiles/default/bin/python3 -V || echo 'Python version failed'",
    "cd backend"
]